### ISSUE TITLE
Ringing correction for pulses is not working

### ISSUE THREAD

**Issue by stephanlphilips** [stephanlphilips/pulse_lib#11]
## bug
When enabling HVI, the pulses exhibit ringing effects (the filter on the FPGA to prevent this seems not to be running).

## feature request
Atm in the config, there is no spec to enable this (in general needed for time domain pulses, but not for freq domain) (reduces BW from 400MHz to 300MHz).

**Comment by sldesnoo-Delft** [comment]
@stephanlphilips, can you add some more information? I assume this applies to the Keysight AWG.
Can you add a screenshot to show the specific problem.

**Comment by stephanlphilips** [comment]
Info about the pulse correction.
[2018_06_18_keysight_pulse_response_overview.pptx](https://github.com/stephanlphilips/pulse_lib/files/4620592/2018_06_18_keysight_pulse_response_overview.pptx)

The correction can be set using the setDigitalFilterMode function (though undocumented in the manual). But hard to debug without AWG :-p

**Comment by sldesnoo-Delft** [comment]
So,  the call setDigitalFilterMode should be added to M3202A driver. 
Should the pulselib always call setDigitalFilterMode(SD_DigitalFilterModes.AOU_FILTER_FLATNESS) ?

**Comment by stephanlphilips** [comment]
I think so, but the mode that is needed depends on the channel type (pulse/MW). Additionally it will also add a delay (the prob depends on the filter type)

**Comment by sldesnoo-Delft** [comment]
How urgent is this problem. Should I try to get some hardware to test it? I can use the rack without digitizer.

**Comment by sldesnoo-Delft** [comment]
The anti-ringing filter is provided in a FPGA bitstream:
/staff-groups/tnw/ns/qt/spin-qubits/equipment/Keysight/Anti-ringing%20filter/firmware_BaseBandPulses_Tap15_4CH_3_73.sbp
/staff-groups/tnw/ns/qt/spin-qubits/equipment/Keysight/Anti-ringing%20filter/firmware_BaseBandPulses_Tap15_4CH_3_77.sbp

**Comment by sldesnoo-Delft** [comment]
The anti-ringing filter will be included in the new AWG firmware with the Pathwave / HVI-2 software update.
