### ISSUE TITLE
Keysight AWG memory partition

### ISSUE THREAD

**Issue by CJvanDiepen** [stephanlphilips/pulse_lib#12]
@sldesnoo-Delft @stephanlphilips 
When uploading a waveform to the Keysight AWG I run into an error as below. I remember it is possible to adjust settings for the memory partitioning. Would it perhaps be helpful to return information to the user about how to adjust these settings, when this error occurs?
![afbeelding](https://user-images.githubusercontent.com/18325492/81784801-af7c0a00-94fd-11ea-8846-b7ddd4823745.png)

**Comment by sldesnoo-Delft** [comment]
@CJvanDiepen, this exception is a genuine bug in the M3202A driver. It should have reported another error. You've uploaded too many waveforms. Waveform memory is not being released.

**Comment by sldesnoo-Delft** [comment]
Fix has been commited to 
https://github.com/sldesnoo-Delft/Qcodes_contrib_drivers branch KeysightM3202A
Now raises a better exception.
