### ISSUE TITLE
Simplify HVI - pulse lib interface

### ISSUE THREAD

**Issue by sldesnoo-Delft** [stephanlphilips/pulse_lib#4]
HVI - pulse lib interface can be simplified using a base class that provides the essential bases.

Proposal HVI base class:

Attributes of HVI base class:
* name of HVI file
* mapping HVI module names to AWGs and digitizers.
* mapping of HVI variables of sequence to HVI registers (for AWG and digitizers)

Methods of HVI base class:
* load(): reads file, assigns modules, compiles and loads to AWG.
* execute(playback_time, n_rep, hvi_variables): writes values to HVI registers and starts HVI
* update_hvi_variables(playback_time, n_rep, hvi_variables): overridable method for user specific hvi variable conversions. Called by execute() before writing HVI registers.

**Comment by stephanlphilips** [comment]
I like the proposal :-)

**Comment by sldesnoo-Delft** [comment]
solved on hvi_refactor branch. Merged into master.
